server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/spirit_ffx?useSSL=false&allowMultiQueries=true
    username: root
    password: ENC@[rDGU93pTlUIbTcYYQJq9cdF4yCP74ykj]
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: select 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: false
          db-type: mysql
          config:
            multi-statement-allow: true
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        login-username: druid
        login-password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: true
  redis:
    database: 0
    host: ${redis.host:localhost}
    port: ${redis.port:6379}
    pool:
      min-idle: 10
      max-idle: 50
      max-active: 200
      max-wait: 3000
  data:
    mongodb:
      host: localhost
      port: 27017
      database: spiritsyslog
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
spirit:
  kaptcha: true
  singleUser: true
  safeCheck: true
  ldapurl: ldap://hna.net:389/